# Generated by Django 5.1.4 on 2024-12-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_logo', models.URLField()),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=250)),
                ('posted_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
                ('employee_type', models.CharField(max_length=50)),
                ('skills', models.JSONField()),
                ('location_type', models.JSONField()),
                ('compensation', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('job_link', models.URLField()),
            ],
        ),
    ]
