# Generated by Django 5.1.4 on 2024-12-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectjob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
    ]
