# Generated by Django 5.1.4 on 2024-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectjob', '0002_remove_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default=''),
        ),
    ]
