# Generated by Django 5.1.4 on 2024-12-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectjob', '0004_alter_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_link',
            field=models.URLField(max_length=2000),
        ),
    ]
